version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: 3000
      FULL_URL: http://localhost:3000/
      DB_HOST: db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chucknoris
      MYSQL_PASSWORD: root_password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:

